


CREATE TABLE IF NOT EXISTS `mydb`.`AT_APT_TRADE` (
  `AT_ID` INT(11) NOT NULL COMMENT '매매거래를 증명하는 일련번호 (in부동산거래계약신고필증) , format : xxxxx-xxxxx',
  `AT_PNU` BIGINT(20) NULL COMMENT '필지고유번호 : 17~19자리 정수, 법정동(8-10) + 토지구분(1)+ 지번(본번4/부번4)',
  `AT_TRADE_DATETIME` VARCHAR(50) NULL COMMENT '거래일자',
  `AT_NAME` VARCHAR(50) NULL COMMENT '아파트 단지명',
  `AT_GPS` VARCHAR(50) NULL COMMENT 'GPS 좌표 (y,x; 위도경도) (format ex : 126.7692711,37.50877829) ',
  `AT_GIS` BIGINT(20) NULL COMMENT 'GIS 건물통합식별번호 (정수 20자리) ',
  `AT_TRADE_AMOUNT` INT(11) NULL COMMENT '매매가격',
  `AT_RANTAL_RATE` INT(11) NULL COMMENT '전세가율',
  `AT_MEMO` VARCHAR(100) NULL,
  `AT_INSERT_DATETIME` DATETIME NULL,
  PRIMARY KEY (`AT_ID`),
  UNIQUE INDEX `AT_PNU_UNIQUE` (`AT_PNU` ASC) VISIBLE,
  UNIQUE INDEX `AT_TRADE_DATETIME_UNIQUE` (`AT_TRADE_DATETIME` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '아파트 거래 정보 테이블 ';


CREATE TABLE IF NOT EXISTS `mydb`.`RC_REGION_CODE` (
  `RC_ID` INT(11) NOT NULL,
  `RC_REGION_CODE` VARCHAR(45) NULL COMMENT '지역코드',
  `RC_SIDO_CODE` VARCHAR(45) NULL COMMENT '시도코드',
  `RC_SGG_CODE` VARCHAR(45) NULL COMMENT '시군구코드 ',
  `RC_UMD_CODE` VARCHAR(45) NULL COMMENT '읍면동 코드',
  `RC_RI_CODE` VARCHAR(45) NULL COMMENT '리 코드',
  `RC_LOCATJUMIN_CODE` VARCHAR(45) NULL COMMENT '지역코드_주민',
  `RC_LOCATJIJUK_CODE` VARCHAR(45) NULL COMMENT '지역코드_지적',
  `RC_LOCATADD_NAME` VARCHAR(45) NULL COMMENT '지역주소명',
  `RC_LOCAT_ORDER` VARCHAR(45) NULL COMMENT '서열',
  `RC_LOCATE_RM` VARCHAR(45) NULL COMMENT '비고',
  `RC_LOCATHIGH_CODE` VARCHAR(45) NULL COMMENT '상위지역코드',
  `RC_LOCALLOW_NAME` VARCHAR(45) NULL COMMENT '하위지역명',
  `RC_ADPT_DATE` VARCHAR(45) NULL COMMENT '생성일',
  PRIMARY KEY (`RC_ID`),
  UNIQUE INDEX `REGION_CODE_UNIQUE` (`RC_REGION_CODE` ASC) VISIBLE,
  UNIQUE INDEX `SIDO_CODE_UNIQUE` (`RC_SIDO_CODE` ASC) VISIBLE,
  UNIQUE INDEX `SGG_CODE_UNIQUE` (`RC_SGG_CODE` ASC) VISIBLE,
  UNIQUE INDEX `UMD_CODE_UNIQUE` (`RC_UMD_CODE` ASC) VISIBLE,
  UNIQUE INDEX `RI_CODE_UNIQUE` (`RC_RI_CODE` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '법정동 코드 테이블';

