

-- 아파트 매매 거래정보 테이블 (로그성 테이블)
CREATE TABLE IF NOT EXISTS `realty`.`TB_APT_TRADE` (
  `AT_ID` VARCHAR(20) NOT NULL COMMENT '매매거래를 증명하는 일련번호 (in부동산거래계약신고필증) , format : xxxxx-xxxxx',
  `AT_PNU` BIGINT(20) NULL COMMENT '필지고유번호 : 17~19자리 정수, 법정동(8-10) + 토지구분(1)+ 지번(본번4/부번4)',
  `AT_NAME` VARCHAR(50) NULL COMMENT '아파트 단지명',
  `AT_TRADE_AMOUNT` INT(11) NULL COMMENT '매매가격 (단위 : 만원)',
  `AT_TRADE_DATE` VARCHAR(50) NULL COMMENT '거래일자',
  `AT_INSERT_DATETIME` DATETIME NULL COMMENT '데이터 생성일자',
  INDEX `AT_PNU_INDEX` (`AT_PNU`),
  INDEX `AT_TRADE_DATE_INDEX` (`AT_TRADE_DATE`),
  PRIMARY KEY (`AT_ID`)
)
ENGINE = InnoDB
COMMENT = '아파트 매매 거래 정보 테이블 ';

-- 아파트 전월세 거래 정보 테이블 (로그성 테이블)
CREATE TABLE IF NOT EXISTS `realty`.`TB_APT_RENT` (
  `AR_PNU` BIGINT(20) NULL COMMENT '필지고유번호 : 17~19자리 정수, 법정동(8-10) + 토지구분(1)+ 지번(본번4/부번4)',
  `AR_NAME` VARCHAR(50) NULL COMMENT '아파트 단지명',
  `AR_CONTRACT_TYPE` VARCHAR(10) NULL COMMENT '계약구분',
  `AR_DEAL_YEAR` VARCHAR(20) NULL COMMENT '계약연도',
  `AR_DEAL_MONTH` VARCHAR(2) NULL COMMENT '계약월',
  `AR_DEAL_DAY` VARCHAR(45) NULL,
  `AR_TERM` VARCHAR(20) NULL COMMENT '계약기간',
  `AR_DEPOSIT` VARCHAR(10) NULL COMMENT '보증금액',
  `AR_MONTHLY_RENT` VARCHAR(10) NULL COMMENT '월세금액',
  `AR_INSERT_DATETIME` DATETIME NULL COMMENT '데이터 생성일자',
  UNIQUE INDEX `AR_PNU_UNIQUE` (`AR_PNU` ASC))
ENGINE = InnoDB
COMMENT = '아파트 전월세 거래 정보 테이블 (로그성 테이블)';

-- 부동산 투자정보 테이블 
CREATE TABLE IF NOT EXISTS `realty`.`TB_REALTY_INFO` (
  `RI_PNU` BIGINT(20) NULL COMMENT '필지고유번호 : 17~19자리 정수, 법정동(8-10) + 토지구분(1)+ 지번(본번4/부번4)',
  `RI_NAME` VARCHAR(45) NULL COMMENT '아파트 단지명',
  `RI_GPS` VARCHAR(50) NULL COMMENT 'GPS 좌표 (y,x; 위도경도) (format ex : 126.7692711,37.50877829) ',
  `RI_GIS` BIGINT(20) NULL COMMENT 'GIS 건물통합식별번호 (정수 20자리)',
  `RI_UNIT_COST` INT(11) NULL COMMENT '평단가',
  `RI_RANTAL_RATE` INT(11) NULL COMMENT '전세가율',
  `RI_MENO` VARCHAR(100) NULL,
  `RI_TYPE` VARCHAR(10) NULL COMMENT '부동산 타입 (단독주택, 빌라/연립, 아파트, 오피스텔 등) ',
  `RI_INSERT_DATETIME` DATETIME NULL COMMENT '데이터 생성일자',
  `RI_UPDATE_DATETIME` DATETIME NULL COMMENT '데이터 수정일자',
  UNIQUE INDEX `RI_PNU_UNIQUE` (`RI_PNU` ASC))
ENGINE = InnoDB
COMMENT = '부동산 투자정보 테이블';




-- 지역코드 테이블 
CREATE TABLE IF NOT EXISTS `realty`.`TB_REGION_CODE` (
  `RC_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `RC_LOCATADD_NAME` VARCHAR(45) NULL DEFAULT '' COMMENT '지역주소명',
  `RC_REGION_CODE` BIGINT(20) NULL DEFAULT 0 COMMENT '지역코드 (10자리)',
  `RC_SIDO_CODE` INT(2) UNSIGNED NULL DEFAULT 0 COMMENT '시도코드 (2자리)',
  `RC_SGG_CODE` INT(3) UNSIGNED NULL DEFAULT 0 COMMENT '시군구코드 (3자리) ',
  `RC_UMD_CODE` INT(3) UNSIGNED NULL DEFAULT 0 COMMENT '읍면동 코드 (3자리) ',
  `RC_RI_CODE` INT(2) UNSIGNED NULL DEFAULT 0 COMMENT '리 코드 (2자리)',
  `RC_LOCATJUMIN_CODE` VARCHAR(45) NULL DEFAULT '' COMMENT '지역코드_주민',
  `RC_LOCATJIJUK_CODE` VARCHAR(45) NULL DEFAULT '' COMMENT '지역코드_지적',
  `RC_LOCAT_ORDER` VARCHAR(45) NULL DEFAULT '' COMMENT '서열',
  `RC_LOCATE_RM` VARCHAR(45) NULL DEFAULT '' COMMENT '비고',
  `RC_LOCATHIGH_CODE` VARCHAR(45) NULL DEFAULT '' COMMENT '상위지역코드',
  `RC_LOCALLOW_NAME` VARCHAR(45) NULL DEFAULT '' COMMENT '하위지역명',
  `RC_INSERT_DATETIME` DATETIME NULL COMMENT '데이터 생성일자',
  PRIMARY KEY (`RC_ID`),
  INDEX `REGION_CODE_UNIQUE` (`RC_REGION_CODE` ASC) VISIBLE,
  INDEX `SIDO_CODE_UNIQUE` (`RC_SIDO_CODE` ASC) VISIBLE,
  INDEX `SGG_CODE_UNIQUE` (`RC_SGG_CODE` ASC) VISIBLE,
  INDEX `UMD_CODE_UNIQUE` (`RC_UMD_CODE` ASC) VISIBLE,
  INDEX `RI_CODE_UNIQUE` (`RC_RI_CODE` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '법정동 코드 테이블';


-- 사용자 테이블 
CREATE TABLE IF NOT EXISTS realty.TB_USER_INFO (
    `UI_ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `UI_USER_ID` varchar(20) DEFAULT NULL COMMENT '사용자 ID',
    `UI_USER_PW` varchar(20) NOT NULL COMMENT '사용자 PW',
    `UI_USER_NAME` varchar(50) NOT NULL COMMENT '사용자명',
    PRIMARY KEY (`UI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 정보 테이블 (Manager를 통해 인증 받은 정보)';



-- batch 테스트 테이블 (제거예정)
CREATE TABLE orders (
  id INT NOT NULL AUTO_INCREMENT,
  order_item VARCHAR(45) NULL,
  price INT NULL,
  order_date DATE NULL,
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '주문테이블';


-- batch 테스트 테이블 (제거예정)
CREATE TABLE accounts (
  id INT NOT NULL AUTO_INCREMENT,
  order_item VARCHAR(45) NULL,
  price INT NULL,
  order_date DATE NULL,
  account_date DATE NULL,
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '정산테이블';


-- RealtyServer 테스트 테이블 (제거예정)
CREATE TABLE IF NOT EXISTS realty.TB_APP_INFO (
  AI_ID VARCHAR(36) NOT NULL,
  AI_NAME VARCHAR(45) NULL,
  AI_PROXY_IP VARCHAR(45) NULL,
  AI_PROXY_PORT INT(10) NULL,
  AI_PROTOCOL VARCHAR(45) NULL,
  AI_URI VARCHAR(1024) NULL,
  AI_DESCRIPTION VARCHAR(45) NULL,
  PRIMARY KEY (AI_ID))
ENGINE = InnoDB;
